package com.mapifesto.domain.dynamic_tag

object DynamicTagsData {
    val allTags = listOf(
        DynamicOsmTagSpecifics(
            id = 1,
            weight = 0,
            url = "https://wiki.openstreetmap.org/wiki/Names",
            description = "The primary name: in general, the most prominent signposted name or the most common name in the local language(s).",
            imageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/6/61/Helena%2C_Montana.jpg/300px-Helena%2C_Montana.jpg",
            name = "Name",
            allowFreeText = true,
            allowedKeys = listOf("name"),
            defaultKey = "name",
            urlTitle = "Names on Osm Wiki"
        ),
        DynamicOsmTagSpecifics(
            id = 2,
            weight = 0,
            name = "Opening Hours",
            defaultKey = "opening_hours",
        ),
        DynamicOsmTagSpecifics(
            id = 3,
            weight = 0,
            url = "https://wiki.openstreetmap.org/wiki/Key:wikidata",
            description = "The ID of the Wikidata item about the feature.",
            imageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/6/66/Wikidata-logo-en.svg/300px-Wikidata-logo-en.svg.png",
            name = "Wikidata",
            allowFreeText = true,
            allowedKeys = listOf("wiki", "wikidata"),
            defaultKey = "wikidata"
        ),
        DynamicOsmTagSpecifics(
            id = 4,
            weight = 950,
            url = "https://wiki.openstreetmap.org/wiki/Key:phone",
            description = "A telephone number associated with the object. The number should be in the format +<country code> <area code> <local number>." +
                    "\nExample: +46 77 1757575\nYou may omit the country code if it is +46.",
            imageUrl = "https://wiki.openstreetmap.org/w/images/thumb/7/76/Phone-number-on-a-shop.jpg/300px-Phone-number-on-a-shop.jpg",
            name = "Phone",
            allowFreeText = true,
            regex = """^\+(?:[0-9] ?){6,14}[0-9]$""".toRegex(),
            allowedKeys = listOf("phone", "contact:phone"),
            defaultKey = "phone"
        ),
        DynamicOsmTagSpecifics(
            id = 5,
            weight = 940,
            url = "https://wiki.openstreetmap.org/wiki/Key:website",
            description = "Specifying the link to the official website for a feature.",
            imageUrl = "https://upload.wikimedia.org/wikipedia/commons/1/10/Vista-www.png",
            name = "Website",
            allowFreeText = true,
            freeTextMustBeUrl = true,
            allowedKeys = listOf("website", "contact:website"),
            defaultKey = "website"
        ),
        DynamicOsmTagSpecifics(
            id = 6,
            weight = 930,
            url = "https://wiki.openstreetmap.org/wiki/Key:wheelchair",
            description = "Indicate if a special place can be used with wheelchairs.",
            imageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0c/Wheelchair_symbol.svg/300px-Wheelchair_symbol.svg.png",
            name = "Wheelchair",
            allowFreeText = false,
            allowedKeys = listOf("wheelchair"),
            defaultKey = "wheelchair",
            maySelectOutOfList = false,
            maySelectSeveral = false,
            suggestedValues = listOf("yes", "no", "limited", "designated",)
        ),
        DynamicOsmTagSpecifics(
            id = 7,
            weight = 990,
            url = "https://wiki.openstreetmap.org/wiki/Key:cuisine",
            description = "For describing the type of food served at an eating place.",
            imageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Burger_and_fries_%281%29.jpg/300px-Burger_and_fries_%281%29.jpg",
            name = "Cuisine",
            suggestedValues = listOf("asian", "balkan", "barbeque", "burger", "chinese", "churro", "coffee_shop", "danish", "donut", "fish", "french", "greek", "hot_dog", "ice_cream", "indian", "italian", "japanese", "kebab", "korean", "langos", "lebanese", "mediterranean", "pasta", "pizza", "ramen", "sandwich", "sausage", "steak_house", "sushi", "tapas", "tex-mex", "thai", "vietnamese", "waffle",),
            defaultKey = "cuisine",
            maySelectOutOfList = true,
            maySelectSeveral = true,
        ),
        DynamicOsmTagSpecifics(
            id = 8,
            weight = 980,
            url = "https://wiki.openstreetmap.org/wiki/Key:diet",
            description = "Select an exclusive diet option for this place. Example: if vegetarian is selected, vegan can not also be selected.",
            imageUrl = "",
            name = "Diet",
            suggestedValues = listOf("pescetarian","vegetarian","vegan","gluten_free","halal","kosher"),
            defaultKey = "diet",
            maySelectOutOfList = true,
            maySelectSeveral = true,
        ),
        DynamicOsmTagSpecifics(
            id = 9,
            weight = 970,
            url = "https://wiki.openstreetmap.org/wiki/Key:takeaway",
            description = "Whether the restaurant offers meals for pick-up that can be consumed elsewhere.",
            imageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/9/97/Yummp_hk_lunchbox.jpg/300px-Yummp_hk_lunchbox.jpg",
            name = "Takeaway",
            suggestedValues = listOf("yes", "no", "only"),
            defaultKey = "takeaway",
            maySelectOutOfList = true,
            maySelectSeveral = false,
        ),
        DynamicOsmTagSpecifics(
            id = 10,
            weight = 960,
            url = "https://wiki.openstreetmap.org/wiki/Key:delivery",
            description = "Sets whether the restaurant or shop offers delivery service.",
            imageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f7/Manila_Philippines_Pizza-Taxi-in-Makati-Business-District-01.jpg/300px-Manila_Philippines_Pizza-Taxi-in-Makati-Business-District-01.jpg",
            name = "Delivery",
            suggestedValues = listOf("yes","no","only"),
            defaultKey = "delivery",
            maySelectOutOfList = true,
            maySelectSeveral = false,
        ),
        DynamicOsmTagSpecifics(
            id = 11,
            weight = 910,
            url = "https://wiki.openstreetmap.org/wiki/Key:indoor_seating",
            description = "To indicate if a restaurant or similar feature offers indoor seating.",
            imageUrl = "",
            name = "Indoor seating",
            suggestedValues = listOf("yes", "no", "bar_table"),
            defaultKey = "indoor_seating",
            maySelectOutOfList = true,
            maySelectSeveral = false,
        ),
        DynamicOsmTagSpecifics(
            id = 12,
            weight = 900,
            url = "https://wiki.openstreetmap.org/wiki/Key:outdoor_seating",
            description = "To indicate if a restaurant or similar feature offers outdoor seating.",
            imageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/Outdoor_seating_area_-_Sussex_Street_-_geograph.org.uk_-_1257513.jpg/300px-Outdoor_seating_area_-_Sussex_Street_-_geograph.org.uk_-_1257513.jpg",
            name = "Outdoor seating",
            suggestedValues = listOf("yes", "no"),
            defaultKey = "outdoor_seating",
            maySelectOutOfList = true,
            maySelectSeveral = false,
        ),
        DynamicOsmTagSpecifics(
            id = 13,
            weight = 220,
            url = "https://wiki.openstreetmap.org/wiki/Key:microbrewery",
            description = "Location houses a microbrewery",
            imageUrl = "https://wiki.openstreetmap.org/w/images/thumb/1/1b/Microbrewery.jpg/300px-Microbrewery.jpg",
            name = "Microbrewery",
            suggestedValues = listOf("yes", "no"),
            defaultKey = "microbrewery",
            maySelectOutOfList = true,
            maySelectSeveral = false,
        ),
        DynamicOsmTagSpecifics(
            id = 14,
            weight = 890,
            url = "https://wiki.openstreetmap.org/wiki/Key:brewery",
            description = "Indicate which breweries' beer this location have available. If it is selling beer from several different breweries, separate the names using a semicolon.",
            imageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/b/ba/Fuller%27s_and_The_Swan.jpg/300px-Fuller%27s_and_The_Swan.jpg",
            name = "Brewery",
            allowFreeText = true,
            defaultKey = "brewery",
        ),
        DynamicOsmTagSpecifics(
            id = 15,
            weight = 430,
            url = "https://wiki.openstreetmap.org/wiki/Key:ice_cream",
            description = "To indicate if a shop or amenity sells ice cream.",
            imageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/7/77/Dessert_with_ice_cream_at_Greens_in_San_Francisco.jpg/300px-Dessert_with_ice_cream_at_Greens_in_San_Francisco.jpg",
            name = "Ice cream",
            suggestedValues = listOf("yes", "no"),
            defaultKey = "ice_cream",
            maySelectOutOfList = true,
            maySelectSeveral = false,
        ),
        DynamicOsmTagSpecifics(
            id = 16,
            weight = 790,
            url = "https://wiki.openstreetmap.org/wiki/Key:drive_through",
            description = "To indicate if an amenity offers a drive-through service.",
            imageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Drive-through_ATM.jpg/300px-Drive-through_ATM.jpg",
            name = "Drive through",
            suggestedValues = listOf("yes", "no"),
            defaultKey = "drive_through",
            maySelectOutOfList = true,
            maySelectSeveral = false,
        ),
        DynamicOsmTagSpecifics(
            id = 17,
            weight = 780,
            url = "https://wiki.openstreetmap.org/wiki/Key:drive_in",
            description = "To indicate if a cinema is a drive-in cinema or a restaurant offers drive-in service.",
            imageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/Autokino_gravenbruch.jpg/300px-Autokino_gravenbruch.jpg",
            name = "Drive in",
            suggestedValues = listOf("yes", "no"),
            defaultKey = "drive_in",
            maySelectOutOfList = true,
            maySelectSeveral = false,
        ),
        DynamicOsmTagSpecifics(
            id = 18,
            weight = 750,
            url = "https://wiki.openstreetmap.org/wiki/Key:capacity",
            description = "Describes the capacity a facility is suitable for.",
            imageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/7/70/Maximum_occupancy_sign%2C_Ohio_University_Convocation_Center.jpg/300px-Maximum_occupancy_sign%2C_Ohio_University_Convocation_Center.jpg",
            name = "Capacity",
            allowFreeText = true,
            allowedKeys = listOf("capacity"),
            defaultKey = "capacity"
        ),
        DynamicOsmTagSpecifics(
            id = 19,
            weight = 260,
            url = "https://wiki.openstreetmap.org/wiki/Key:distillery",
            description = "Location sells distilled beverage from named distillery.",
            imageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/5/52/Bar_Hard_Rock_Cafe_Prague.png/300px-Bar_Hard_Rock_Cafe_Prague.png",
            name = "Distillery",
            allowFreeText = true,
            defaultKey = "distillery",
        ),
        DynamicOsmTagSpecifics(
            id = 20,
            weight = 940,
            url = "https://wiki.openstreetmap.org/wiki/Key:drink",
            description = "Used to specify specific drinks served or sold.",
            imageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/6/62/Klappermelk_kelapa_muda.jpg/300px-Klappermelk_kelapa_muda.jpg",
            name = "Drink",
            suggestedValues = listOf("yes","no","sales","served","draught","bottled","takeaway",),
            defaultKey = "drink",
            maySelectOutOfList = true,
            maySelectSeveral = true,
        ),
        DynamicOsmTagSpecifics(
            id = 21,
            weight = 880,
            url = "https://wiki.openstreetmap.org/wiki/Key:reservation",
            description = "Whether a reservation is applicable before a visit.",
            imageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/Receptionist.jpg/300px-Receptionist.jpg",
            name = "Reservation",
            suggestedValues = listOf("yes","no","required","recommended","members_only",),
            defaultKey = "reservation",
            maySelectOutOfList = true,
            maySelectSeveral = true,
        ),
        DynamicOsmTagSpecifics(
            id = 22,
            weight = 250,
            url = "https://wiki.openstreetmap.org/wiki/Key:license_classes",
            description = "Specifying categories that are taught in a driving school.",
            imageUrl = "",
            name = "License classes",
            allowFreeText = true,
            defaultKey = "license_classes",
        ),
        DynamicOsmTagSpecifics(
            id = 23,
            weight = 560,
            url = "https://wiki.openstreetmap.org/wiki/Key:fee",
            description = "Yes or no, to indicate if money is charged to use this facility.",
            imageUrl = "",
            name = "Fee",
            suggestedValues = listOf("yes","no","donation"),
            defaultKey = "fee",
            maySelectOutOfList = true,
            maySelectSeveral = false,
        ),
        DynamicOsmTagSpecifics(
            id = 24,
            weight = 600,
            url = "https://wiki.openstreetmap.org/wiki/Key:min_age",
            description = "Minimum age for a person to enter or use a facility.",
            imageUrl = "",
            name = "Min age",
            allowFreeText = true,
            defaultKey = "min_age",
            numberOnly = true,
        ),
        DynamicOsmTagSpecifics(
            id = 25,
            weight = 590,
            url = "https://wiki.openstreetmap.org/wiki/Key:max_age",
            description = "Maximum age for a person to enter or use a facility.",
            imageUrl = "",
            name = "Max age",
            allowFreeText = true,
            defaultKey = "max_age",
            numberOnly = true,
        ),
        DynamicOsmTagSpecifics(
            id = 26,
            weight = 550,
            url = "https://wiki.openstreetmap.org/wiki/Key:books",
            description = "Further information, if only special kind of books sold at a bookshop.",
            imageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/5/59/Gatchina_books.jpg/300px-Gatchina_books.jpg",
            name = "Books",
            suggestedValues = listOf("academic","anarchism","antiquarian","children","comic","discount","religion","erotic","textbook"),
            defaultKey = "books",
            maySelectOutOfList = true,
            maySelectSeveral = true,
        ),
        DynamicOsmTagSpecifics(
            id = 27,
            weight = 380,
            url = "https://wiki.openstreetmap.org/wiki/Key:operator",
            description = "Сompany, corporation, person or any other entity who is directly in charge of the current operation of a map object.",
            imageUrl = "",
            name = "Operator",
            allowFreeText = true,
            defaultKey = "operator",
        ),
        DynamicOsmTagSpecifics(
            id = 28,
            weight = 370,
            url = "https://wiki.openstreetmap.org/wiki/Key:operator:type",
            description = "Defines the type of operator.",
            imageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f6/US_Navy_050411-N-8629M-049_Non-governmental_organization_Project_HOPE_volunteers_Andrew_Garrett%2C_MD%2C_center%2C_and_Michael_Polifka%2C_MD%2C_examine_an_Indonesian_child.jpg/300px-thumbnail.jpg",
            name = "Operator type",
            suggestedValues = listOf("public","private","government","religious","ngo","community","consortium","cooperative"),
            defaultKey = "operator:type",
            maySelectOutOfList = true,
            maySelectSeveral = true,
        ),
        DynamicOsmTagSpecifics(
            id = 29,
            weight = 410,
            url = "https://wiki.openstreetmap.org/wiki/Key:branch",
            description = "Identifies which branch of a brand or chain this object represents, or controversially the name of a branch railway.",
            imageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/Porter_Ranch_Bank_of_America.jpg/300px-Porter_Ranch_Bank_of_America.jpg",
            name = "Branch",
            allowFreeText = true,
            defaultKey = "branch",
        ),
        DynamicOsmTagSpecifics(
            id = 30,
            weight = 540,
            url = "https://wiki.openstreetmap.org/wiki/Key:atm",
            description = "A cash point/ATM (Automated Teller Machine) is available at this location.",
            imageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Fr%C3%BCher_Bankautomat_von_Nixdorf_retouched.jpg/300px-Fr%C3%BCher_Bankautomat_von_Nixdorf_retouched.jpg",
            name = "Atm",
            suggestedValues = listOf("yes","no"),
            defaultKey = "atm",
            maySelectOutOfList = true,
            maySelectSeveral = false,
        ),
        DynamicOsmTagSpecifics(
            id = 31,
            weight = 400,
            url = "https://wiki.openstreetmap.org/wiki/Key:brand",
            description = "The identity of a specific product, service, or business. Often trademarks.",
            imageUrl = "https://wiki.openstreetmap.org/w/images/thumb/8/80/Shell_logo.jpg/300px-Shell_logo.jpg",
            name = "Brand",
            allowFreeText = true,
            defaultKey = "brand",
        ),
        DynamicOsmTagSpecifics(
            id = 32,
            weight = 390,
            url = "",
            description = "Website of the brand.",
            imageUrl = "",
            name = "Brand website",
            allowFreeText = true,
            freeTextMustBeUrl = true,
            defaultKey = "brand:website",
        ),
        DynamicOsmTagSpecifics(
            id = 33,
            weight = 530,
            url = "https://wiki.openstreetmap.org/wiki/Key:theatre:genre",
            description = "A genre of theatre.",
            imageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/Theatre_Masks_SVG.svg/300px-Theatre_Masks_SVG.svg.png",
            name = "Theatre genre",
            suggestedValues = listOf("drama","comedy","opera","musical","ballet","philharmonic","chamber_music","figure","puppet","marionette","shadow_play","cabaret","boulevard","circus","stand_up_comedy","political","variety"),
            defaultKey = "theatre:genre",
            maySelectOutOfList = true,
            maySelectSeveral = true,
        ),
        DynamicOsmTagSpecifics(
            weight = 520,
            url = "https://wiki.openstreetmap.org/wiki/Key:theatre:type",
            description = "Type of theatre interior or layout.",
            imageUrl = "",
            name = "Theatre type",
            suggestedValues = listOf("amphi","open_air","concert_hall","opera_house","stage"),
            defaultKey = "theatre:type",
            maySelectOutOfList = true,
            maySelectSeveral = true,
        ),
        DynamicOsmTagSpecifics(
            weight = 860,
            url = "https://wiki.openstreetmap.org/wiki/Key:religion",
            description = "Defines the specific religion.",
            imageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6c/Religious_syms.svg/300px-Religious_syms.svg.png",
            name = "Religion",
            suggestedValues = listOf("buddhist","christian","hindu","jain","jewish","muslim","pagan","shinto","sikh","taoist","zoroastrian","animist","antoinist","bahai","benzhu","caodaism","chinese_folk","confucian","shamanic","scientologist","self-realization_fellowship","spiritualist","voodoo","yazidi","multifaith"),
            defaultKey = "religion",
            maySelectOutOfList = true,
            maySelectSeveral = true,
        ),
        DynamicOsmTagSpecifics(
            weight = 850,
            url = "https://wiki.openstreetmap.org/wiki/Key:denomination",
            description = "Defines the subspecies of a specific religion.",
            imageUrl = "",
            name = "Denomination",
            suggestedValues = listOf("catholic","roman_catholic","sunni","baptist","orthodox","lutheran","anglican","protestant","methodist","russian_orthodox","greek_orthodox","evangelical","presbyterian","pentecostal","jehovahs_witness","mormon","shia","seventh_day_adventist","reformed","serbian_orthodox","ukrainian_greek_catholic","episcopal","greek_catholic"),
            defaultKey = "denomination",
            maySelectOutOfList = true,
            maySelectSeveral = true,
        ),
        DynamicOsmTagSpecifics(
            weight = 460,
            url = "https://wiki.openstreetmap.org/wiki/Key:winery",
            description = "Location sells wines from named winery.",
            imageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a0/Tempranillowine.jpg/300px-Tempranillowine.jpg",
            name = "Winery",
            allowFreeText = true,
            defaultKey = "winery",
        ),
        DynamicOsmTagSpecifics(
            weight = 450,
            url = "https://wiki.openstreetmap.org/wiki/Key:bakehouse",
            description = "Indicates that the bakery has its own bakery.",
            imageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c8/R%C3%BChrger%C3%A4t_in_B%C3%A4ckerei_DSCF3175.JPG/300px-R%C3%BChrger%C3%A4t_in_B%C3%A4ckerei_DSCF3175.JPG",
            name = "Bakehouse",
            suggestedValues = listOf("yes","no"),
            defaultKey = "bakehouse",
            maySelectOutOfList = true,
            maySelectSeveral = false,
        ),
        DynamicOsmTagSpecifics(
            weight = 580,
            url = "https://wiki.openstreetmap.org/wiki/Key:origin",
            description = "Tag to desribe the origin, e.g. the country of origin, for the goods of a shop.",
            imageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/6/63/International_flag_globe.png/300px-International_flag_globe.png",
            name = "Origin",
            suggestedValues = listOf("african",	"arab",	"argentinian",	"asian",	"balkan",	"basque",	"brazilian",	"chinese",	"croatian",	"czech",	"french",	"german",	"greek",	"hungarian",	"indian",	"iranian",	"italian",	"japanese",	"korean",	"latin_american",	"lebanese",	"mexican",	"peruvian",	"polish",	"romanian",	"russian",	"spanish",	"thai",	"turkish",),
            defaultKey = "origin",
            maySelectOutOfList = true,
            maySelectSeveral = true,
        ),
        DynamicOsmTagSpecifics(
            weight = 440,
            url = "https://wiki.openstreetmap.org/wiki/Key:oven",
            description = "The oven tag is used to describe a type of an oven.",
            imageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Pizza-oven.jpg/300px-Pizza-oven.jpg",
            name = "Oven",
            suggestedValues = listOf("wood_fired","electric","gas_fired","no"),
            defaultKey = "oven",
            maySelectOutOfList = true,
            maySelectSeveral = false,
        ),
        DynamicOsmTagSpecifics(
            weight = 570,
            url = "https://wiki.openstreetmap.org/wiki/Key:fair_trade",
            description = "Whether you can have fair trade food or products.",
            imageUrl = "https://upload.wikimedia.org/wikipedia/commons/0/02/Fairtrade-logo.jpg",
            name = "Fair trade",
            suggestedValues = listOf("yes","no"," only"),
            defaultKey = "fair_trade",
            maySelectOutOfList = true,
            maySelectSeveral = false,
        ),
        DynamicOsmTagSpecifics(
            weight = 740,
            url = "https://wiki.openstreetmap.org/wiki/Key:clothes",
            description = "Further information on the kind of clothes sold at a clothes shop.",
            imageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Hasseen2.jpg/300px-Hasseen2.jpg",
            name = "Clothes",
            suggestedValues = listOf("babies","children","costumes","denim","fashion","fur","hats","leather","maternity","men","motorcycle","oversize","schoolwear","sports","suits","swimwear","traditional","underwear","unisex","wedding","women","women;men","women;men;children","workwear"),
            defaultKey = "clothes",
            maySelectOutOfList = true,
            maySelectSeveral = true,
        ),
        DynamicOsmTagSpecifics(
            weight = 730,
            url = "https://wiki.openstreetmap.org/wiki/Key:second_hand",
            description = "Whether a shop, dedicated to a specific kind of good, sells second-hand items.",
            imageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/7/76/Second_hand_clothes.jpg/300px-Second_hand_clothes.jpg",
            name = "Second hand",
            suggestedValues = listOf("yes","no", "only"),
            defaultKey = "second_hand",
            maySelectOutOfList = true,
            maySelectSeveral = false,
        ),
        DynamicOsmTagSpecifics(
            weight = 720,
            url = "https://wiki.openstreetmap.org/wiki/Key:shoes",
            description = "Tagged on shops and other features to denote if they sell shoes or not and what type of shoes they sell.",
            imageUrl = "",
            name = "Shoes",
            suggestedValues = listOf("yes","no"),
            defaultKey = "shoes",
            maySelectOutOfList = true,
            maySelectSeveral = false,
        ),
        DynamicOsmTagSpecifics(
            weight = 300,
            url = "https://wiki.openstreetmap.org/wiki/Key:tailor:alteration_service",
            description = "Specifies whether alteration and repair of clothes are done by this tailor.",
            imageUrl = "",
            name = "Tailor alteration service",
            suggestedValues = listOf("yes","no"),
            defaultKey = "tailor:alteration_service",
            maySelectOutOfList = true,
            maySelectSeveral = false,
        ),
        DynamicOsmTagSpecifics(
            weight = 290,
            url = "https://wiki.openstreetmap.org/wiki/Key:tailor:bespoke_tailoring",
            description = "Specifies whether clothing are made to buyer's specification by this tailor.",
            imageUrl = "",
            name = "Tailor bespoke tailoring",
            suggestedValues = listOf("yes","no"),
            defaultKey = "tailor_bespoke_tailoring",
            maySelectOutOfList = true,
            maySelectSeveral = false,
        ),
        DynamicOsmTagSpecifics(
            weight = 840,
            url = "https://wiki.openstreetmap.org/wiki/Key:beauty",
            description = "To indicate the services in a beauty shop.",
            imageUrl = "",
            name = "Beauty",
            suggestedValues = listOf("nails","tanning","cosmetics","spa","skin_care","waxing","hair_removal","eyebrow","aesthetic","massage","eyelash"),
            defaultKey = "beauty",
            maySelectOutOfList = true,
            maySelectSeveral = true,
        ),
        DynamicOsmTagSpecifics(
            weight = 510,
            url = "https://wiki.openstreetmap.org/wiki/Key:repair",
            description = "Information whether a dedicated shop does repair.",
            imageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Espresso_machine_repair_shop.png/300px-Espresso_machine_repair_shop.png",
            name = "Repair",
            suggestedValues = listOf("yes","no","only","electronics","computer","tv","motorcycle","assisted_self_service"),
            defaultKey = "repair",
            maySelectOutOfList = true,
            maySelectSeveral = true,
        ),
        DynamicOsmTagSpecifics(
            weight = 710,
            url = "https://wiki.openstreetmap.org/wiki/Key:music",
            description = "Describes which kind of music is performed or sold at a feature.",
            imageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/0/02/Stonehaven_live_%40_PPC_Graz.jpg/300px-Stonehaven_live_%40_PPC_Graz.jpg",
            name = "Music",
            suggestedValues = listOf("yes","no","live","recorded","vinyl","jazz","sheet"),
            defaultKey = "music",
            maySelectOutOfList = true,
            maySelectSeveral = true,
        ),
        DynamicOsmTagSpecifics(
            weight = 700,
            url = "https://wiki.openstreetmap.org/wiki/Key:music_genre",
            description = "",
            imageUrl = "",
            name = "Music genre",
            suggestedValues = listOf("Fado","jazz","rock","metal","blues","independent","electro;techno","alternative","classical;jazz","Après␣Ski","Jazz","independent","␣punk","␣metal","Electronic","rock;␣jazz;␣kayokyoku","schlager","soul","Hip␣hop","punk","Trance","␣Progressive␣Trance","␣Goa","classical","RnB","␣hip␣hop","jazz␣&␣blues"),
            defaultKey = "music_genre",
            maySelectOutOfList = true,
            maySelectSeveral = true,
        ),
        DynamicOsmTagSpecifics(
            weight = 670,
            url = "https://wiki.openstreetmap.org/wiki/Key:sauna",
            description = "Type of sauna in the amenity.",
            imageUrl = "",
            name = "Sauna",
            suggestedValues = listOf("yes", "no", "hot","steam","smoke","dry","hanjeungmak","aroma","infrared"),
            defaultKey = "sauna",
            maySelectOutOfList = true,
            maySelectSeveral = true,
        ),
        DynamicOsmTagSpecifics(
            weight = 660,
            url = "https://wiki.openstreetmap.org/wiki/Key:swimming_pool",
            description = "Shows whether a feature has a swimming pool or not.",
            imageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7c/Le_Meridien_Nirwana_Bali_Villa_private_pool_%282926930162%29.jpg/300px-Le_Meridien_Nirwana_Bali_Villa_private_pool_%282926930162%29.jpg",
            name = "Swimming pool",
            suggestedValues = listOf("yes","no","inground","outdoor","above","personal","swimming","wadeing","swimming_pool","kids","indoor","spa","children's_pool","covered","heated","plunge","outdoors","paddling_pool","roof_top","abandoned","wave_pool","hot_tub","pool","water"),
            defaultKey = "swimming_pool",
            maySelectOutOfList = true,
            maySelectSeveral = true,
        ),
        DynamicOsmTagSpecifics(
            weight = 650,
            url = "https://wiki.openstreetmap.org/wiki/Key:personal_trainer",
            description = "",
            imageUrl = "",
            name = "Personal trainer",
            suggestedValues = listOf("yes","no"),
            defaultKey = "personal_trainer",
            maySelectOutOfList = true,
            maySelectSeveral = false,
        ),
        DynamicOsmTagSpecifics(
            weight = 640,
            url = "https://wiki.openstreetmap.org/wiki/Key:self_service",
            description = "Indicates whether an object is self service.",
            imageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/3/35/SelfCRR.jpg/300px-SelfCRR.jpg",
            name = "Self service",
            suggestedValues = listOf("yes","no","only","partially"),
            defaultKey = "self_service",
            maySelectOutOfList = true,
            maySelectSeveral = false,
        ),
        DynamicOsmTagSpecifics(
            weight = 830,
            url = "https://wiki.openstreetmap.org/wiki/Key:stars",
            description = "Used to classify or rate certain places (e.g. restaurants, hotels, camp sites).",
            imageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/6/63/5_star_superior_hotel.jpg/300px-5_star_superior_hotel.jpg",
            name = "Stars",
            allowFreeText = true,
            defaultKey = "stars",
        ),
        DynamicOsmTagSpecifics(
            weight = 820,
            url = "https://wiki.openstreetmap.org/wiki/Key:rooms",
            description = "Amount of rooms available for guests.",
            imageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f9/Hobbs%27s_architecture-_containing_designs_and_ground_plans_for_villas%2C_cottages_and_other_edifices%2C_both_suburban_and_rural%2C_adapted_to_the_United_States._With_rules_for_criticism%2C_and_introduction_%2814589729948%29.jpg/300px-thumbnail.jpg",
            name = "Rooms",
            allowFreeText = true,
            defaultKey = "rooms",
            numberOnly = true,
        ),
        DynamicOsmTagSpecifics(
            weight = 810,
            url = "https://wiki.openstreetmap.org/wiki/Key:beds",
            description = "The number of beds in a hotel or hospital.",
            imageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/9/95/Quadruple_Room_four_beds_1_-_Paris_Opera_Cadet_Hotel.jpg/300px-Quadruple_Room_four_beds_1_-_Paris_Opera_Cadet_Hotel.jpg",
            name = "Beds",
            allowFreeText = true,
            defaultKey = "beds",
            numberOnly = true,
        ),
        DynamicOsmTagSpecifics(
            weight = 800,
            url = "https://wiki.openstreetmap.org/wiki/Key:internet_access",
            description = "Indicates if an object offers internet access. The access can be with given computers or WLAN access. The only limitation is that the internet access has to be public.",
            imageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/7/70/Applications-internet.svg/300px-Applications-internet.svg.png",
            name = "Internet access",
            suggestedValues = listOf("yes","no","wlan","terminal","service","wired"),
            defaultKey = "internet_access",
            maySelectOutOfList = true,
            maySelectSeveral = true,
        ),
        DynamicOsmTagSpecifics(
            weight = 630,
            url = "https://wiki.openstreetmap.org/wiki/Key:museum",
            description = "Type of museum classified by topic.",
            imageUrl = "",
            name = "Museum",
            suggestedValues = listOf("art","gallery","transport","railway","aviation","aerospace","maritime","science","apis_mellifera","nature","technology","agriculture","paleontology","history","living_history","military","war","archaeological","open_air","local","children","ethnography","person","language","health"),
            defaultKey = "museum",
            maySelectOutOfList = true,
            maySelectSeveral = true,
        ),
        DynamicOsmTagSpecifics(
            weight = 620,
            url = "https://wiki.openstreetmap.org/wiki/Key:subject",
            description = "Used for the kind of object or subject in museum's exhibition.",
            imageUrl = "",
            name = "Subject",
            suggestedValues = listOf("arts","ceramics","cinematography","history","music","nature","railway","science","railway","science"),
            defaultKey = "subject",
            maySelectOutOfList = true,
            maySelectSeveral = true,
        ),
        DynamicOsmTagSpecifics(
            weight = 610,
            url = "https://wiki.openstreetmap.org/wiki/Key:museum_type",
            description = "Type of museum with regard to the operator/level.",
            imageUrl = "",
            name = "Museum type",
            suggestedValues = listOf("municipal","departmental","republican","national","private","public","institutional","regional","provincial"),
            defaultKey = "museum_type",
            maySelectOutOfList = true,
            maySelectSeveral = true,
        ),
        DynamicOsmTagSpecifics(
            weight = 230,
            url = "https://wiki.openstreetmap.org/wiki/Key:covered",
            description = "A property to denote if an object is covered by something.",
            imageUrl = "https://wiki.openstreetmap.org/w/images/thumb/d/dc/Covered.jpg/300px-Covered.jpg",
            name = "Covered",
            suggestedValues = listOf("yes", "no","arcade","colonnade","partial","booth"),
            defaultKey = "covered",
            maySelectOutOfList = true,
            maySelectSeveral = false,
        ),
        DynamicOsmTagSpecifics(
            weight = 480,
            url = "https://wiki.openstreetmap.org/wiki/Key:automated",
            description = "Indicates whether an object is operated automatically.",
            imageUrl = "",
            name = "Automated",
            suggestedValues = listOf("yes","no"),
            defaultKey = "automated",
            maySelectOutOfList = true,
            maySelectSeveral = false,
        ),
        DynamicOsmTagSpecifics(
            weight = 350,
            url = "https://wiki.openstreetmap.org/wiki/Key:vacuum_cleaner",
            description = "Whether a service station has a vacuum cleaner.",
            imageUrl = "",
            name = "Vacuum cleaner",
            suggestedValues = listOf("yes","no"),
            defaultKey = "vacuum_cleaner",
            maySelectOutOfList = true,
            maySelectSeveral = false,
        ),
        DynamicOsmTagSpecifics(
            weight = 340,
            url = "",
            description = "Do customers have to pay extra to use the vacuum cleaner, even if they already paid for the car wash?",
            imageUrl = "",
            name = "Vacuum cleaner fee",
            suggestedValues = listOf("yes","no"),
            defaultKey = "vacuum_cleaner:fee",
            maySelectOutOfList = true,
            maySelectSeveral = false,
        ),
        DynamicOsmTagSpecifics(
            weight = 330,
            url = "",
            description = "Does the customer have to operate the vacuum cleaner themselves?",
            imageUrl = "",
            name = "Vacuum cleaner self service",
            suggestedValues = listOf("yes","no"),
            defaultKey = "vacuum_cleaner:self_service",
            maySelectOutOfList = true,
            maySelectSeveral = false,
        ),
        DynamicOsmTagSpecifics(
            weight = 320,
            url = "",
            description = "If the vacuum cleaner has different opening hours from the service station.",
            imageUrl = "",
            name = "Vacuum cleaner opening hours",
            suggestedValues = listOf("yes","no"),
            defaultKey = "vacuum_cleaner:opening_hours",
            maySelectOutOfList = true,
            maySelectSeveral = false,
        ),
        DynamicOsmTagSpecifics(
            weight = 280,
            url = "https://wiki.openstreetmap.org/wiki/Key:garden:type",
            description = "",
            imageUrl = "",
            name = "Garden type",
            suggestedValues = listOf("botanical","community","residential","roof_garden","green_wall","show_garden","arboretum"),
            defaultKey = "garden:type",
            maySelectOutOfList = true,
            maySelectSeveral = true,
        ),
        DynamicOsmTagSpecifics(
            weight = 270,
            url = "https://wiki.openstreetmap.org/wiki/Key:garden:style",
            description = "The general type and purpose of a given garden.",
            imageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bb/Botanical_garden_Krakow_%282006-05-13%29_04.jpg/300px-Botanical_garden_Krakow_%282006-05-13%29_04.jpg",
            name = "Garden style",
            suggestedValues = listOf("english","french","chinese","japanese","persian","zen","monastery","rosarium","herb_garden","medical_garden","kitchen","flower_garden","cottage_garden","walled_garden"),
            defaultKey = "garden:style",
            maySelectOutOfList = true,
            maySelectSeveral = true,
        ),
        DynamicOsmTagSpecifics(
            weight = 310,
            url = "https://wiki.openstreetmap.org/wiki/Key:truck_wash",
            description = "Indicates that a service station has a truck wash.",
            imageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/9/96/Truck_Wash_-_geograph.org.uk_-_233407.jpg/300px-Truck_Wash_-_geograph.org.uk_-_233407.jpg",
            name = "Truck wash",
            suggestedValues = listOf("yes","no"),
            defaultKey = "truck_wash",
            maySelectOutOfList = true,
            maySelectSeveral = false,
        ),
        DynamicOsmTagSpecifics(
            weight = 210,
            url = "https://wiki.openstreetmap.org/wiki/Key:castle_type",
            description = "A classification of the castle.",
            imageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c6/Castle_of_Belcastel_20.jpg/300px-Castle_of_Belcastel_20.jpg",
            name = "Castle type",
            suggestedValues = listOf("defensive","palace","stately","manor","fortress","castrum","shiro","kremlin","hillfort","fortified_church"),
            defaultKey = "castle_type",
            maySelectOutOfList = true,
            maySelectSeveral = true,
        ),
        DynamicOsmTagSpecifics(
            weight = 190,
            url = "https://wiki.openstreetmap.org/wiki/Key:screen",
            description = "Describes the number of screens in a venue.",
            imageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/Football_match_in_cinema.jpg/300px-Football_match_in_cinema.jpg",
            name = "Screen",
            allowFreeText = true,
            defaultKey = "screen",
            numberOnly = true,
        ),
        DynamicOsmTagSpecifics(
            weight = 140,
            url = "https://wiki.openstreetmap.org/wiki/Key:golf:course",
            description = "Number of holes within a golf course.",
            imageUrl = "",
            name = "Golf course",
            suggestedValues = listOf("number + _hole","pitch_and_putt","driving_range"),
            defaultKey = "golf:course",
            maySelectOutOfList = true,
            maySelectSeveral = false,
        ),
        DynamicOsmTagSpecifics(
            weight = 130,
            url = "",
            description = "Difficulty of a golf course.",
            imageUrl = "",
            name = "Golf par",
            allowFreeText = true,
            defaultKey = "golf:par",
            numberOnly = true,
        ),
        DynamicOsmTagSpecifics(
            weight = 1120,
            url = "https://wiki.openstreetmap.org/wiki/Key:government",
            description = "Indicates the subtypes of government agencies and institutions.",
            imageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/The_Parliament_of_Sri_Lanka.jpg/300px-The_Parliament_of_Sri_Lanka.jpg",
            name = "Government",
            suggestedValues = listOf("aerospace","archive","audit","administrative","bailiff","border_control","cadaster","culture","customs","data_protection","education","election_commission","environment","forestry","healthcare","immigration","intelligence","investigation","it","legislative","migration","military","ministry","pension_fund","parliament","police","presidency","prosecutor","public_safety","public_service","public_utility","recruitment","register_office","residents_registration_office","senate","social_security","social_services","social_welfare","statistics","tax","town_council","transportation","treasury","water_utility_company","youth_welfare_department"),
            defaultKey = "government",
            maySelectOutOfList = true,
            maySelectSeveral = true,
        ),
        DynamicOsmTagSpecifics(
            weight = 110,
            url = "https://wiki.openstreetmap.org/wiki/Key:emergency",
            description = "This key describe various emergency services.",
            imageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/1/16/Krankenwagen_in_Berlin._April_2020.jpg/300px-Krankenwagen_in_Berlin._April_2020.jpg",
            name = "Emergency",
            suggestedValues = listOf("yes","no"),
            defaultKey = "emergency",
            maySelectOutOfList = true,
            maySelectSeveral = false,
        ),
        DynamicOsmTagSpecifics(
            weight = 100,
            url = "",
            description = "If a law office or lawyer advertises that they practice particular fields of law.",
            imageUrl = "",
            name = "Lawyer speciality",
            suggestedValues = listOf("bankruptcy","corporate","civil_rights","criminal","employment","entertainment","environmental","estate","family","health","immigration","intellectual_property","international","maritime","military","personal_injury","real_estate","tax"),
            defaultKey = "lawyer:speciality",
            maySelectOutOfList = true,
            maySelectSeveral = true,
        ),
        DynamicOsmTagSpecifics(
            weight = 420,
            url = "https://wiki.openstreetmap.org/wiki/Key:massage",
            description = "Type of massage.",
            imageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0d/Thaisun4.jpg/300px-Thaisun4.jpg",
            name = "Massage",
            suggestedValues = listOf("chinese","thai","acupressure","therapeutic","chiropractic","shiatsu"),
            defaultKey = "massage",
            maySelectOutOfList = true,
            maySelectSeveral = true,
        ),
        DynamicOsmTagSpecifics(
            weight = 90,
            url = "https://wiki.openstreetmap.org/wiki/Key:historic:civilization",
            description = "Describe roughly which civilization (or ancient culture) has built a feature or is somehow else connected to it.",
            imageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/5/56/Fig._9_mapa.jpg/300px-Fig._9_mapa.jpg",
            name = "Historic civilization",
            allowFreeText = true,
            defaultKey = "historic:civilization",
        ),
        DynamicOsmTagSpecifics(
            weight = 80,
            url = "https://wiki.openstreetmap.org/wiki/Key:historic:memorial",
            description = "Small memorials, usually remembering special persons, people who lost their lives in the wars, past events or missing places.",
            imageUrl = "https://wiki.openstreetmap.org/w/images/thumb/f/f2/CIMG4191.JPG/300px-CIMG4191.JPG",
            name = "Historic memorial",
            allowFreeText = true,
            suggestedValues = listOf("memorial", "artist_name",	"architect", "start_date", "inscription",),
            defaultKey = "historic:memorial",
        ),
        DynamicOsmTagSpecifics(
            weight = 70,
            url = "https://wiki.openstreetmap.org/wiki/Key:heritage",
            description = "Site/building/object registered by an official heritage organisation.",
            imageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f5/Taj_Mahal_2012.jpg/300px-Taj_Mahal_2012.jpg",
            name = "Heritage",
            allowFreeText = true,
            defaultKey = "heritage",
            numberOnly = true,
        ),
        DynamicOsmTagSpecifics(
            weight = 690,
            url = "https://wiki.openstreetmap.org/wiki/Key:musical_instruments",
            description = "A tag for showing which instruments are sold or crafted.",
            imageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/6/63/Boston_1869_catalogue_images_%28re-created_1%29.jpg/300px-Boston_1869_catalogue_images_%28re-created_1%29.jpg",
            name = "Musical instruments",
            suggestedValues = listOf("yes","no"),
            defaultKey = "musical_instruments",
            maySelectOutOfList = true,
            maySelectSeveral = false,
        ),
        DynamicOsmTagSpecifics(
            weight = 770,
            url = "https://wiki.openstreetmap.org/wiki/Key:parking",
            description = "Indicates the type of the parking facility.",
            imageUrl = "",
            name = "Parking",
            suggestedValues = listOf("yes","no","surface","underground","street_side","multi-storey","lane","carports","rooftop","garage_boxes","layby","sheds"),
            defaultKey = "parking",
            maySelectOutOfList = true,
            maySelectSeveral = true,
        ),
        DynamicOsmTagSpecifics(
            weight = 760,
            url = "https://wiki.openstreetmap.org/wiki/Key:sport",
            description = "For categorising any specific sport",
            imageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0c/Sport_balls.svg/300px-Sport_balls.svg.png",
            name = "Sport",
            suggestedValues = listOf("9pin","10pin","american_football","aikido","archery","athletics","australian_football","badminton","bandy","baseball","basketball","beachvolleyball","biathlon","billiards","bmx","bobsleigh","boules","bowls","boxing","bullfighting","canadian_football","canoe","chess","cliff_diving","climbing","climbing_adventure","cockfighting","cricket","crossfit","croquet","curling","cycle_polo","cycling","darts","dog_agility","dog_racing","equestrian","fencing","field_hocdefaultKey","fitness","five-a-side","floorball","free_flying","futsal","gaelic_games","golf","gymnastics","handball","hapkido","horseshoes","horse_racing","ice_hocdefaultKey","ice_skating","ice_stock","jiu-jitsu","judo","karate","karting","kickboxing","kitesurfing","korfball","krachtbal","lacrosse","martial_arts","miniature_golf","model_aerodrome","motocross","motor","multi","netball","obstacle_course","orienteering","paddle_tennis","padel","parachuting","parkour","pedal_car_racing","pelota","pesäpallo","pickleball","pilates","pole_dance","racquet","rc_car","roller_skating","rowing","rugby_league","rugby_union","running","sailing","scuba_diving","shooting","shot-put","skateboard","ski_jumping","skiing","snooker","soccer","speedway","squash","sumo","surfing","swimming","table_tennis","table_soccer","taekwondo","tennis","toboggan","ultimate","volleyball","wakeboarding","water_polo","water_ski","weightlifting","wrestling","yoga","zurkhaneh_sport"),
            defaultKey = "sport",
            maySelectOutOfList = true,
            maySelectSeveral = true,
        ),
        DynamicOsmTagSpecifics(
            weight = 360,
            url = "https://wiki.openstreetmap.org/wiki/Key:bath_type",
            description = "Public bath type.",
            imageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Blue_Lagoon_2012-08-23_%284%29.JPG/300px-Blue_Lagoon_2012-08-23_%284%29.JPG",
            name = "Bath type",
            suggestedValues = listOf("hot_spring","onsen","hammam","thermal","river","lake","sea","ashiyu"),
            defaultKey = "bath_type",
            maySelectOutOfList = true,
            maySelectSeveral = true,
        ),
        DynamicOsmTagSpecifics(
            weight = 180,
            url = "https://wiki.openstreetmap.org/wiki/Key:recycling_type",
            description = "A tag to differentiate between big recycling centers and just simple recycling containers.",
            imageUrl = "https://wiki.openstreetmap.org/w/images/thumb/c/c2/WertstoffhofWeitnau.jpg/300px-WertstoffhofWeitnau.jpg",
            name = "Recycling type",
            suggestedValues = listOf("container","centre"),
            defaultKey = "recycling_type",
            maySelectOutOfList = true,
            maySelectSeveral = false,
        ),
        DynamicOsmTagSpecifics(
            weight = 170,
            url = "https://wiki.openstreetmap.org/wiki/Key:social_facility",
            description = "A facility that provides social services.",
            imageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/4/42/Social_sciences.svg/300px-Social_sciences.svg.png",
            name = "Social facility",
            suggestedValues = listOf("group_home","nursing_home","assisted_living","outreach","shelter","food_bank","ambulatory_care","day_care","workshop","healthcare","social_club","soup_kitchen","advice","hospice","community_centre","childrens_centre","retirement_home"),
            defaultKey = "social_facility",
            maySelectOutOfList = true,
            maySelectSeveral = true,
        ),
        DynamicOsmTagSpecifics(
            weight = 160,
            url = "https://wiki.openstreetmap.org/wiki/Key:vending",
            description = "Specifies the items sold by a vending machine.",
            imageUrl = "https://wiki.openstreetmap.org/w/images/thumb/8/89/Jt_osm_vending_chemist.jpg/300px-Jt_osm_vending_chemist.jpg",
            name = "Vending",
            suggestedValues = listOf("yes","no", "parking_tickets","excrement_bags","cigarettes","public_transport_tickets","drinks","fuel","parcel_pickup;parcel_mail_in","parcel_pickup","sweets","newspapers","food","condoms","coffee","bicycle_tube","milk","water","bread","stamps","elongated_coin","movies","drinks;food","chewing_gums"),
            defaultKey = "vending",
            maySelectOutOfList = true,
            maySelectSeveral = true,
        ),
        DynamicOsmTagSpecifics(
            weight = 150,
            url = "https://wiki.openstreetmap.org/wiki/Key:zoo",
            description = "Describes the type of zoo.",
            imageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fc/Jaguar.jpg/300px-Jaguar.jpg",
            name = "Zoo",
            suggestedValues = listOf("aviary","birds","butterfly","enclosure","falconry","petting_zoo","reptile","safari_park","wildlife_park"),
            defaultKey = "zoo",
            maySelectOutOfList = true,
            maySelectSeveral = true,
        ),
        DynamicOsmTagSpecifics(
            weight = 60,
            url = "",
            description = "What types of pet can be bought here?",
            imageUrl = "",
            name = "Pet",
            suggestedValues = listOf("dogs", "cats", "rabbits", "guinea pigs", "lizards", "hamsters", "fish", "rats", "birds", "snakes", "tortoises", "turtles", "sea monkeys", "ferrets",),
            defaultKey = "pet",
            maySelectOutOfList = true,
            maySelectSeveral = true,
        ),
        DynamicOsmTagSpecifics(
            weight = 200,
            url = "",
            description = "Does the cinema do 3D movies (where you wear the special glasses)?",
            imageUrl = "",
            name = "Cinema 3D",
            suggestedValues = listOf("yes","no"),
            defaultKey = "cinema:3D",
            maySelectOutOfList = false,
            maySelectSeveral = false,
        ),
        DynamicOsmTagSpecifics(
            weight = 509,
            url = "https://wiki.openstreetmap.org/wiki/Key:attraction",
            description = "Covers all kinds of dedicated attractions.",
            imageUrl = "https://wiki.openstreetmap.org/w/images/thumb/2/23/Autoscooter1.jpg/300px-Autoscooter1.jpg",
            name = "Attraction",
            suggestedValues = listOf("amusement_ride", "animal", "big_wheel", "bumper_car", "bungee_jumping", "carousel", "dark_ride", "drop_tower", "formal_garden", "game_installation", "kiddie_ride", "log_flume", "maze", "pirate_ship",
                "river_rafting", "rock_art", "roller_coaster", "summer_tobagan", "swing_carousel", "train", "tropic", "water_slide", "boat_ride"),
            defaultKey = "attraction",
            maySelectOutOfList = false,
            maySelectSeveral = false,
        ),
    )

    fun getDynamicTagByName(tagName: String): DynamicOsmTagSpecifics? {
        return allTags.firstOrNull {it.name == tagName}
    }

    fun getDynamicTagById(tagId: Int): DynamicOsmTagSpecifics? {
        return allTags.firstOrNull {it.id == tagId}
    }
}